### ISSUE TITLE
Always visible even if content is smaller than its container

### ISSUE THREAD

**Issue by odbayar** [utatti/perfect-scrollbar#443]
Is there a way to make the scrollbar's rail always visible even if content is smaller than its container?

The rail's height doesn't get set when content is smaller than its container.

**Comment by slimandslam** [comment]
+1

**Comment by noraesae** [comment]
Sorry for the late response. There is no native way to do this. If there is any good idea to handle this, please upload a PR. Any other form of contribution will be also welcomed.

**Comment by devolkpl** [comment]
+1

**Comment by gmareater** [comment]
+1

**Comment by utatti** [comment]
Now the activeness of axis can be checked by `ps--active-?` class in CSS. You can simply modify the `display` styles in `perfect-scrollbar.css`.

```css
.ps > .ps__rail-x {
  display: none; /* remove this! */
  ...
}

.ps > .ps__rail-y {
  display: none; /* remove this! */
  ...
}

.ps.ps--active-x > .ps__rail-x,
.ps.ps--active-y > .ps__rail-y {
  display: block; /* remove this! */
  ...
}
```
